-- 1. Create order_status_history table
CREATE TABLE IF NOT EXISTS public.order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to avoid duplicates
DROP POLICY IF EXISTS "Allow select for order history owner or admin" ON public.order_status_history;
DROP POLICY IF EXISTS "Allow admins to manage all status history" ON public.order_status_history;

-- 4. Define policies
CREATE POLICY "Allow select for order history owner or admin"
ON public.order_status_history FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.orders 
        WHERE orders.id = order_status_history.order_id 
        AND (
            (auth.uid() IS NOT NULL AND orders.user_id = auth.uid()) OR
            (public.is_admin() = true) OR
            (orders.user_id IS NULL)
        )
    )
);

CREATE POLICY "Allow admins to manage all status history"
ON public.order_status_history FOR ALL
USING (public.is_admin() = true)
WITH CHECK (public.is_admin() = true);

-- 5. Trigger function to automatically log status updates
CREATE OR REPLACE FUNCTION public.handle_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Insert on new order creation
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.order_status_history (order_id, status, created_at)
    VALUES (NEW.id, NEW.order_status, NEW.created_at);
  -- Insert on update only if the status has actually changed
  ELSIF (TG_OP = 'UPDATE' AND OLD.order_status IS DISTINCT FROM NEW.order_status) THEN
    INSERT INTO public.order_status_history (order_id, status, created_at)
    VALUES (NEW.id, NEW.order_status, NOW());
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Trigger binding
DROP TRIGGER IF EXISTS on_order_status_changed ON public.orders;
CREATE TRIGGER on_order_status_changed
  AFTER INSERT OR UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.handle_order_status_change();
